import Head from 'next/head'
import Avatar from '../components/Avatar'
import { MicrophoneIcon, ViewGridIcon } from '@heroicons/react/solid'
import Image from 'next/image'
import { SearchIcon } from '@heroicons/react/outline'
import Footer from '../components/Footer'
import { useRef } from 'react'
import { useRouter } from 'next/router'



export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);

  const search = (e) => {
    e.preventDefault();
    const term = searchInputRef.current.value;

    if(!term) return;

    router.push(`/search?term=${term}`);

  }

  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Koogle - Powered by Google API</title>
        <meta name="description" content="Generated by create next app, powered by Google API" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/*Header*/}
      <header className="flex w-full p-5 justify-between text-sm text-gray-700">
            <div className="flex space-x-4 items-center">
                <p className="link">About</p>
                <p className="link">Store</p>
            </div>

            <div className="flex space-x-4 items-center">
                <p className="link">Gmail</p>
                <p className="link">Images</p>
                <ViewGridIcon className="h-10 w-10 p-2 rounded-full transition duration-150 transform hover:scale-110 bg-gray-100 cursor-pointer"/>
                <Avatar url="https://www.nj.com/resizer/h8MrN0-Nw5dB5FOmMVGMmfVKFJo=/450x0/smart/cloudfront-us-east-1.images.arcpublishing.com/advancelocal/SJGKVE5UNVESVCW7BBOHKQCZVE.jpg"/>
            </div>
        </header>

      {/*Body*/}
        <form className="flex flex-col items-center mt-44 flex-grow w-4/5">
          <Image 
            src="https://i.extraimage.info/pix/aYgd0.jpg"
            width={300}
            height={100}
          />
          <div className="flex w-full mt-5 border border-gray-200 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl">
            <SearchIcon className="h-5 mr-3 text-gray-500"/>
            <input ref={searchInputRef} type="text" className="flex-grow focus:outline-none" />
            <MicrophoneIcon className="h-5 ml-3"/>
          </div>
          <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:flex-row sm:space-y-0 sm:space-x-4">
            <button onClick={search} className="btn">Google Search</button>
            <button onClick={search} className="btn">I'm Feeling Lucky</button>
          </div>
        </form>
      {/*Footer*/}
        <Footer />


      
    </div>
  )
}
